dist: trusty
sudo: false
language: node_js
node_js: '8.10'
cache: yarn
install:
- yarn
jobs:
  include:
    - stage:  lint
      script: yarn lint
    # - stage:  test
    #   script: yarn test
    # - stage:  coverage
    #   script: yarn test:coverage
    - stage: publish
      deploy:
        provider: script
        script: "yarn build && cp .npmrc.template $HOME/.npmrc && npm publish --access public"
        skip_cleanup: true
        on:
          tags: true
